version: '2'
services:
    front_balancer:
        build:
            context: ./APP-LB-RoundRobin
            dockerfile: Dockerfile
        container_name: front_balancer
        ports:
            - 80:80
        links:
            - logservice1
            - logservice2
            - logservice3
        depends_on:
            - logservice1
            - logservice2
            - logservice3
    logservice1:
        build:
            context: ./logService
            dockerfile: Dockerfile
        container_name: logservice1
        ports:
            - 34001:6000
        depends_on:
            - db
    logservice2:
        build:
            context: ./logService
            dockerfile: Dockerfile
        container_name: logservice2
        ports:
            - 34002:6000
        depends_on:
            - db
    logservice3:
        build:
            context: ./logService
            dockerfile: Dockerfile
        container_name: logservice3
        ports:
            - 34003:6000
        depends_on:
            - db
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
volumes:
    mongodb:
    mongodb_config: